language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm i -g npm@version-number
  - npm install express mocha chai
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
script: test
cache:
  yarn: true